version: "3.9"
services:
  dcbot:
    build: .
    env_file: .env
    depends_on:
      - lavalink
    volumes:
      - ./:/App

  lavalink:
    image: fredboat/lavalink:dev
    volumes:
      - ./Lavalink-Workdir/application.yml:/opt/Lavalink/application.yml
