version: "3.9"
services:
  dcbot:
    build: .
    env_file: .env
    depends_on:
      - lavalink
    volumes:
      - ./:/App
    restart: unless-stopped

  lavalink:
    image: fredboat/lavalink:latest
    volumes:
      - ./lavalink-config.yml:/opt/Lavalink/application.yml
    restart: unless-stopped
